# initialize i2c and i2c for esp32 mcu
CONFIG_I2C=y
CONFIG_I2C_ESP32=y
# initialize gpio for IO btn and leds
CONFIG_GPIO=y
# initialize mpu6050 and sensor driver
CONFIG_SENSOR=y
CONFIG_MPU6050=y
# initialize driver logs for debugging
CONFIG_LOG=y
CONFIG_I2C_LOG_LEVEL_DBG=y